apiVersion: v1
data:
  kubesphere.yaml: |
    authentication:
      authenticateRateLimiterMaxTries: 10
      authenticateRateLimiterDuration: 10m0s
      loginHistoryRetentionPeriod: 168h
      maximumClockSkew: 10s
      jwtSecret: {{ .Values.authentication.jwtSecret | quote }}
kind: ConfigMap
metadata:
  name: devops-plugin-config
